# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1e8e7741b155ca397ddfecabf4f8c57a01f6b40ca122e7dc43d0e06093fbe4b42fb68cb8dbde2d359cf7f6ec27076cce39cf36ba70f3d3ed82f4e9d902cf9d9

test:
  secret_key_base: c40d457d20e47f18b6966c124f3b95f10fe576249a463c9e3170af49c2b4453876e1bf9f8027013c39847e118efc645e366c47c0240f368d105c93a06013561b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
